---
- hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: Update Debian
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Update RedHat
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - ansible.builtin.package:
        name:
          - wrk
        state: present

- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 1 containous/whoami"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: wrk 1
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output


- hosts: master
  tasks:
    - name: Scale for 2 instances in the master
      command: "docker service scale whoami=2"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: wrk 2
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_2


- hosts: master
  tasks:
    - name: Scale for 4 instances in the master
      command: "docker service scale whoami=4"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: wrk 4
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_4


- hosts: master
  tasks:
    - name: Scale for 8 instances in the master
      command: "docker service scale whoami=8"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: wrk 8
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_8


    - name: Benchmark Results Output 1 wkr
      ansible.builtin.debug:
        msg: 'Benchmark 1 instance: {{ wrk_output.stdout_lines | select("search", "Req/Sec") }}'
    - name: Benchmark Results Output 2 wkr
      ansible.builtin.debug:
        msg: ' Benchmark 2 instances: {{ wrk_output_2.stdout_lines | select("search", "Req/Sec") }}'
    - name: Benchmark Results Output 4 wkr
      ansible.builtin.debug:
        msg: 'Benchmark 4 instances: {{ wrk_output_4.stdout_lines | select("search", "Req/Sec") }}'
    - name: Benchmark Results Output 8 wkr
      ansible.builtin.debug:
        msg: 'Benchmark 8 instances: {{ wrk_output_8.stdout_lines | select("search", "Req/Sec") }}'




